name: Deploy Documentation

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Setup dummy xdg-open
        run: |
          sudo mv /usr/bin/xdg-open /usr/bin/xdg-open.bak || true
          echo '#!/bin/sh' | sudo tee /usr/bin/xdg-open
          sudo chmod +x /usr/bin/xdg-open

      - name: Build documentation
        run: |
          pnpm docs || {
            echo "Documentation build failed with exit code $?"
            echo "Current directory contents:"
            ls -la
            echo "Docs directory contents:"
            ls -la docs/
            exit 1
          }
        env:
          CI: true
          BROWSER: none
          DEBUG: vitepress:*

      - name: List docs directory
        run: |
          echo "Contents of docs directory:"
          ls -la docs/
          echo "Contents of docs/.vitepress directory:"
          ls -la docs/.vitepress/ || true
          echo "Contents of docs/.vitepress/dist directory:"
          ls -la docs/.vitepress/dist/ || true

      - name: Restore xdg-open
        if: always()
        run: |
          sudo mv /usr/bin/xdg-open.bak /usr/bin/xdg-open || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
